### ISSUE TITLE
Blank columns in the .csv file

### ISSUE THREAD

**Issue by dianegli** [COVID19StatePolicy/SocialDistancing#1]
Not sure if someone already noticed this, but when I tried to pull in the .csv files from here: https://raw.githubusercontent.com/COVID19StatePolicy/SocialDistancing/master/data/USstatesCov19distancingpolicy.csv. I noticed that there were completely blank columns in the file. Isn't a huge issue but thought I'd flag for the future.

**Comment by COVID19StatePolicy** [comment]
Thanks for flagging! This was an oddity in our data processing step. We have replaced the old file with a new one - don't hesitate to let us know if this remains an issue!

**Comment by dianegli** [comment]
Thank you, appreciate the update!
