### ISSUE TITLE
Feature Request (future): Additional granularity on school-related measures

### ISSUE THREAD

**Issue by gnguy** [COVID19StatePolicy/SocialDistancing#2]
Hello,

Thank you for your great work on this project! I was wondering(/requesting) whether you anticipate being able to incorporate additional levels of granularity around education-related social distancing measures in the fall. 

For instance, it seems that some states are considering whether they could implement measures such as staggered attendance days (e.g. M/W/F school for half of the students, T/Th for the other half) or morning/afternoon-split classrooms. If those are implemented in many states, are there plans to measure/track those types of education-related policies that may fall short of full closure? It's likely that such implementation may happen at the district-level (in which case you wouldn't be able to easily track it), but I'm curious about your thoughts if it does end up being state-level guidance rather than at the district-level.

Thanks,
Grant

**Comment by breebangjensen** [comment]
Hi Grant,

Thanks for this comment/suggestion.  Our team is currently exploring ways to capture variation in the ways states ease restrictions in existing policies.  This is certainly something we will keep in mind going forward.
