### ISSUE TITLE
Beta vs Original dataset

### ISSUE THREAD

**Issue by gorzell** [COVID19StatePolicy/SocialDistancing#4]
Hi,
It looks like you are in the process of transitioning to an improved dataset with more columns. At the moment though the BETA `csv` (as noted in the README) is missing quite a bit of the data. It looks like the non-beta `csv` is no longer available in the top level `data/` directory, but has moved to `00_archive`.

Would it be possible to move the non-beta file back to the top level until the BETA file is ready and complete with all of the data? We are pulling this data to pre-populate policies in models for policy makers: https://covid-modeling.org/about, so making sure we are loading the correct source every night is super important.

Worst case we can point at the file in the `00_archive` folder, but I thought I would ask here first.

**Comment by COVID19StatePolicy** [comment]
Hi there,

We're so sorry about that! We were pushing both versions but apparently the full dataset didn't properly populate yesterday. Our sincerest apologies - I hope that hasn't too negatively affected your work. 

All the best,
Nancy

**Comment by COVID19StatePolicy** [comment]
The full dataset is now populated, with updates from yesterday, alongside the BETA dataset. Our apologies again for the snafu!

**Comment by gorzell** [comment]
Thanks so much for the quick response and correction!

**Comment by COVID19StatePolicy** [comment]
Absolutely! Since it has the potential to affect your model/code structure, I'm happy to give you a heads up as we get closer to finishing all of states over to the new format. It'll still be a little bit (maybe a week?), but whatever might be useful for you. Take care!

All the best,
Nancy
