### ISSUE TITLE
Duplicate PID’s in beta CSV

### ISSUE THREAD

**Issue by reececasey** [COVID19StatePolicy/SocialDistancing#8]
Hello, firstly thank you for providing this data source.

I am seeing duplicate entries for the same PID in the beta csv. Around 19 duplicate rows for the same PID however the data does slightly differ which is more the issue. 

Is this an expected behaviour? If so is there anything to indicate which row should be used.

Thanks in advance

**Comment by COVID19StatePolicy** [comment]
Hi there, many thanks for flagging! We will look into this immediately and push an update as soon as possible. There should *not* be an PID duplicates (each entry is meant to be unique); thank you again for bringing this to our attention!

**Comment by COVID19StatePolicy** [comment]
To provide an update: we have pushed an updated dataset fixing the duplicated PIDs and _hopefully_ all policy linkages associated with them. Thank you again for bringing this important feedback to light!
