### ISSUE TITLE
Some Maryland records includes link to Maine website....

### ISSUE THREAD

**Issue by seandavi** [COVID19StatePolicy/SocialDistancing#9]
Just an FYI.

**Comment by COVID19StatePolicy** [comment]
Thanks so much for the flag! We'll update accordingly immediately.

**Comment by COVID19StatePolicy** [comment]
I've just reviewed all Maryland records and no Maine websites appear to be under PolicySource. I've made sure UpdatingSource1 and UpdatingSource2 are all Maryland sites as well. Many thanks again!
